<?php

namespace api\modules\v1\controllers;

use Yii;
use yii\web\Response;
use common\models\ArticleTag;
use common\models\ArticleCategory;
use api\modules\v1\resources\Article;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;
use yii\rest\IndexAction;
use yii\rest\OptionsAction;
use yii\rest\CreateAction;
use yii\rest\UpdateAction;
use yii\rest\DeleteAction;
use yii\rest\Serializer;
use yii\rest\ViewAction;
use yii\web\HttpException;

/**
 * @SWG\Swagger(
 *     schemes={"http","https"},
 *     basePath="/",
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Yii2-Starter-Kit API Documentation",
 *         description="API description...",
 *         termsOfService="",
 *         @SWG\License(
 *             name="BSD License",
 *             url="https://raw.githubusercontent.com/yii2-starter-kit/yii2-starter-kit/master/LICENSE.md"
 *         )
 *     ),
 * )
 * @author Eugene Terentev <eugene@terentev.net>
 */
class ArticleController extends ActiveController
{
    /**
     * @var string
     */
    public $modelClass = 'api\modules\v1\resources\Article';

	public $serializer = [
		'class' => 'yii\rest\Serializer',
		'collectionEnvelope' => 'items',
	];

    /**
     * @SWG\Get(path="/v1/article/index",
     *     tags={"article", "index"},
     *     summary="Retrieves the collection of Articles.",
     *     @SWG\Response(
     *         response = 200,
     *         description = "Article collection response",
     *         @SWG\Schema(ref = "#/definitions/Article")
     *     ),
     * )
     *
     * @SWG\Get(path="/v1/article/view",
     *     tags={"Article"},
     *     summary="Displays data of one article only",
     *     @SWG\Response(
     *         response = 200,
     *         description = "Used to fetch information of a specific article.",
     *         @SWG\Schema(ref = "#/definitions/Article")
     *     ),
     * )
     *
     * @SWG\Options(path="/v1/article/options",
     *     tags={"Article"},
     *     summary="Displays the options for the article resource.",
     *     @SWG\Response(
     *         response = 200,
     *         description = "Displays the options available for the Article resource",
     *         @SWG\Schema(ref = "#/definitions/Article")
     *     ),
     * )
     */
    public function actions()
    {
        return [
            'index' => [
                'class' => IndexAction::class,
                'modelClass' => $this->modelClass,
                'prepareDataProvider' => [$this, 'prepareDataProvider']
            ],
            'view' => [
                'class' => ViewAction::class,
                'modelClass' => $this->modelClass,
                'findModel' => [$this, 'findModel']
            ],
            'options' => [
                'class' => OptionsAction::class,
            ]
        ];
    }

    /**
     * @return ActiveDataProvider
     */
    public function prepareDataProvider()
    {
		$query = Article::find()->with('category', 'articleAttachments', 'tags')->published();
		$request = Yii::$app->request;

		if (!empty(($categorySlug = $request->get('categorySlug')))) {
//			$query->joinWith(['category c'])->andWhere(['c.slug' => $categorySlug]);
			$query->joinWith(['category c' => function($q) {
				$q->joinWith('parent p');
			}])->andWhere(['or', ['c.slug' => $categorySlug], ['p.slug' => $categorySlug]]);
		}

		if (!empty(($tagSlug = $request->get('tagSlug')))) {
			$query->joinWith(['tags t'])->andWhere(['t.slug' => $tagSlug]);
		}

		return new ActiveDataProvider(array(
			'query' => $query,
			'pagination' => [
				'pageSize' => $request->get('perPage') ? $request->get('perPage') : 5,
				'page' => $request->get('currentPage') ? $request->get('currentPage') - 1 : 0,
			],
        ));
    }

    /**
     * @param $id
     * @return array|null|\yii\db\ActiveRecord
     * @throws HttpException
     */
    public function findModel($id)
    {
        $model = Article::find()
            ->published()
            ->andWhere(['id' => (int)$id])
            ->one();
        if (!$model) {
            throw new HttpException(404);
        }
        return $model;
    }

	public function beforeAction($action)
	{
		header('Access-Control-Allow-Origin: *');
		header("Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers");

		Yii::$app->response->format = Response::FORMAT_JSON;

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function actionGetTags()
	{
		return ArticleTag::find()->asArray()->all();
	}

	public function actionGetTag($slug)
	{
		$model = ArticleTag::find()->where(["slug" => (string)$slug])->one();
		if (!$model) {
			throw new HttpException(404);
		}
		return $model;
	}

	public function actionGetSubCategories($parentSlug)
	{
		return ArticleCategory::find()->active()
			->joinWith(['parent p'])->andWhere(['p.slug' => $parentSlug])
			->asArray()->all();
	}
}
