<?php

namespace api\modules\v1\controllers;

use Yii;
use yii\web\Controller;
use common\models\Invitro;
use yii\web\Response;

class InvitroController extends Controller
{
	public function beforeAction($action)
	{
		header('Access-Control-Allow-Origin: *');
		header("Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers");

		Yii::$app->response->format = Response::FORMAT_JSON;

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
    public function actionPoints()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return Invitro::find()->asArray()->all();
    }
}
