<?php

namespace api\modules\v1\controllers;

use Yii;
use yii\web\Response;
use yii\rest\ActiveController;
use yii\rest\ViewAction;
use yii\web\HttpException;
use api\modules\v1\resources\Page;

class PageController extends ActiveController
{
    /**
     * @var string
     */
    public $modelClass = 'api\modules\v1\resources\Page';

	public function beforeAction($action)
	{
		header('Access-Control-Allow-Origin: *');

		Yii::$app->response->format = Response::FORMAT_JSON;

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

    public function actions()
    {
        return [
            'view' => [
                'class' => ViewAction::class,
                'modelClass' => $this->modelClass,
                'findModel' => [$this, 'findModel']
            ],
        ];
    }

    /**
     * @param $id
     * @return array|null|\yii\db\ActiveRecord
     * @throws HttpException
     */
    public function findModel($id)
    {
        $model = Page::find()
            ->published()
            ->andWhere(['id' => (int)$id])
            ->one();
        if (!$model) {
            throw new HttpException(404);
        }
        return $model;
    }

    public function actionTest()
	{
		$model = Page::find()
			->published()
			->andWhere(['id' => 3])
			->one();
		if (!$model) {
			throw new HttpException(404);
		}
		return $model;
	}

	public function actionMyview($id)
	{
		$model = Page::find()
			->published()
			->andWhere(['id' => (int)$id])
			->one();
		if (!$model) {
			throw new HttpException(404);
		}
		return $model;
	}
}
