<?php

namespace api\modules\v1\controllers;

use yii\web\Response;
use yii\web\Controller;
use common\helpers\ChoiceHelper;
use api\modules\v1\resources\Review;

class ReviewController extends Controller
{
	public function beforeAction($action)
	{
		header('Access-Control-Allow-Origin: *');
		header("Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers");

		\Yii::$app->response->format = Response::FORMAT_JSON;

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

    public function actionIndex()
    {
        return Review::find()
			->where(['show_in_slider' => ChoiceHelper::YES, 'status' => Review::STATUS_PUBLISHED])
			->all();
    }
}
