<?php

namespace api\modules\v1\resources;



class SiteSettings extends \common\models\KeyStorageItem
{
	public function fields()
	{
		return ['key', 'value'];
	}

	public function afterFind()
	{
		$this->key = str_replace('site-settings.', '', $this->key);
		parent::afterFind(); // TODO: Change the autogenerated stub
	}
}
